# Generated by Django 5.0.2 on 2024-03-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_user_servicedependency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microservice',
            name='description',
        ),
        migrations.AlterModelTable(
            name='microservice',
            table='dashboard_microservice',
        ),
    ]
