# Generated by Django 5.0.2 on 2024-03-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_microservice_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='microservice',
            name='deployment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
