# Generated by Django 5.0.2 on 2024-03-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_microservice_deployment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='microservice',
            name='deployment_date',
        ),
        migrations.AddField(
            model_name='microservice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
