# Generated by Django 5.0.2 on 2024-03-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_servicedependency_is_admin_dependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedependency',
            name='is_admin_dependency',
            field=models.BooleanField(default=False),
        ),
    ]
