# Generated by Django 5.0.2 on 2024-03-19 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_activitylog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
